from enum import Enum

class Talent(str, Enum):
    INFRAVISION = "infravision"
    FLY = "fly"
    WATER_BREATHING = "water_breathing"
    REGENERATION = "regeneration"
    CAMOUFLAGE = "camouflage"


    """
    other ideas generated by AI for consideration


    SHARP_HEARING = "sharp_hearing"
    ENHANCED_SMELL = "enhanced_smell"
    TELEPATHY = "telepathy"
    ELEMENTAL_AFFINITY = "elemental_affinity"
    SHAPESHIFT = "shapeshift"
    LUMINESCENCE = "luminescence"
    CLIMBING_CLAWS = "climbing_claws"
    SONIC_EMIT = "sonic_emit"
    VENOMOUS_BITE = "venomous_bite"
    CAMOUFLAGE = "camouflage"
    SWIFTNESS = "swift_movement"
    SIZE_SHIFT = "size_shift"

    """
    
