from world.recipes.blacksmithing.iron_dagger import *               # noqa: F401,F403
from world.recipes.blacksmithing.iron_shortsword import *           # noqa: F401,F403
from world.recipes.blacksmithing.iron_longsword import *            # noqa: F401,F403
from world.recipes.blacksmithing.iron_hand_axe import *             # noqa: F401,F403
from world.recipes.blacksmithing.spear import *                     # noqa: F401,F403
from world.recipes.blacksmithing.iron_mace import *                # noqa: F401,F403
from world.recipes.blacksmithing.iron_hammer import *              # noqa: F401,F403
from world.recipes.blacksmithing.bronze_dagger import *             # noqa: F401,F403
from world.recipes.blacksmithing.bronze_shortsword import *         # noqa: F401,F403
from world.recipes.blacksmithing.bronze_longsword import *          # noqa: F401,F403
from world.recipes.blacksmithing.bronze_hand_axe import *           # noqa: F401,F403
from world.recipes.blacksmithing.bronze_spear import *              # noqa: F401,F403
from world.recipes.blacksmithing.bronze_mace import *               # noqa: F401,F403
from world.recipes.blacksmithing.bronze_hammer import *             # noqa: F401,F403
from world.recipes.blacksmithing.ironbound_shield import *          # noqa: F401,F403
from world.recipes.blacksmithing.crossbow import *                 # noqa: F401,F403
from world.recipes.blacksmithing.iron_spiked_club import *         # noqa: F401,F403
from world.recipes.blacksmithing.studded_leather_armor import *    # noqa: F401,F403
from world.recipes.blacksmithing.bronze_greatsword import *        # noqa: F401,F403
from world.recipes.blacksmithing.bronze_battleaxe import *         # noqa: F401,F403
from world.recipes.blacksmithing.bronze_rapier import *            # noqa: F401,F403
from world.recipes.blacksmithing.bronze_greaves import *          # noqa: F401,F403
from world.recipes.blacksmithing.bronze_bracers import *          # noqa: F401,F403
from world.recipes.blacksmithing.bronze_helm import *             # noqa: F401,F403
from world.recipes.blacksmithing.bronze_lantern import *          # noqa: F401,F403
