# Generated by Django 6.0.3 on 2026-04-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_memory", "0003_combat_and_lore_memory"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="combatmemory",
            new_name="ai_memory_c_mob_typ_2d74b3_idx",
            old_name="ai_memory_c_mob_typ_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="combatmemory",
            new_name="ai_memory_c_mob_typ_b0b7a9_idx",
            old_name="ai_memory_c_mob_typ_d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="combatmemory",
            new_name="ai_memory_c_mob_typ_4b3ce1_idx",
            old_name="ai_memory_c_mob_typ_g7h8i9_idx",
        ),
        migrations.RenameIndex(
            model_name="combatmemory",
            new_name="ai_memory_c_mob_nam_7c3be8_idx",
            old_name="ai_memory_c_mob_nam_j0k1l2_idx",
        ),
        migrations.RenameIndex(
            model_name="lorememory",
            new_name="ai_memory_l_scope_l_eb5c56_idx",
            old_name="ai_memory_l_scope_l_m3n4o5_idx",
        ),
        migrations.RenameIndex(
            model_name="lorememory",
            new_name="ai_memory_l_scope_l_cb6311_idx",
            old_name="ai_memory_l_scope_l_p6q7r8_idx",
        ),
        migrations.RenameIndex(
            model_name="npcmemory",
            new_name="ai_memory_n_npc_id_191033_idx",
            old_name="ai_memory_n_npc_id_a1b2c3_idx",
        ),
        migrations.RenameIndex(
            model_name="npcmemory",
            new_name="ai_memory_n_npc_id_5b0b23_idx",
            old_name="ai_memory_n_npc_id_d4e5f6_idx",
        ),
        migrations.RenameIndex(
            model_name="npcmemory",
            new_name="ai_memory_n_npc_nam_19c14b_idx",
            old_name="ai_memory_n_npc_na_g7h8i9_idx",
        ),
        migrations.RenameIndex(
            model_name="npcmemory",
            new_name="ai_memory_n_npc_nam_0e71bd_idx",
            old_name="ai_memory_n_npc_na_j0k1l2_idx",
        ),
        migrations.AlterField(
            model_name="combatmemory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="lorememory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="npcmemory",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
