"""
Social command definitions — data-driven registry.

Each social defines message variants for:
  - no_target_self / no_target_room — used when no argument given
  - target_self / target_room / target_victim — used with a target
  - self_self / self_room — used when targeting yourself

Room messages use Evennia's $You()/$conj() substitution.
Direct messages use {actor}/{target} placeholders.
"""

SOCIALS = {
    "applaud": {
        "no_target_self": "You give a round of applause.",
        "no_target_room": "$You() $conj(give) a round of applause.",
        "target_self": "You applaud {target}'s performance.",
        "target_room": "$You() $conj(applaud) {target}'s performance.",
        "target_victim": "{actor} applauds your performance.",
        "self_self": "You applaud yourself.",
        "self_room": "$You() $conj(applaud) $pron(yourself).",
    },
    "blush": {
        "no_target_self": "Your cheeks turn bright red.",
        "no_target_room": "$You() $conj(blush).",
        "target_self": "You blush at {target}.",
        "target_room": "$You() $conj(blush) at {target}.",
        "target_victim": "{actor} blushes at you.",
        "self_self": "You blush at your own reflection.",
        "self_room": "$You() $conj(blush) at $pron(their) own reflection.",
    },
    "bounce": {
        "no_target_self": "You bounce around the room excitedly!",
        "no_target_room": "$You() $conj(bounce) around the room excitedly!",
        "target_self": "You bounce excitedly in front of {target}.",
        "target_room": "$You() $conj(bounce) excitedly in front of {target}.",
        "target_victim": "{actor} bounces excitedly in front of you.",
        "self_self": "You bounce around like a maniac.",
        "self_room": "$You() $conj(bounce) around like a maniac.",
    },
    "bow": {
        "no_target_self": "You bow gracefully.",
        "no_target_room": "$You() $conj(bow) gracefully.",
        "target_self": "You bow before {target}.",
        "target_room": "$You() $conj(bow) before {target}.",
        "target_victim": "{actor} bows before you.",
        "self_self": "You bow to yourself... how odd.",
        "self_room": "$You() $conj(bow) to $pron(yourself)... how odd.",
    },
    "cackle": {
        "no_target_self": "You throw back your head and cackle with glee!",
        "no_target_room": "$You() $conj(throw) back $pron(their) head and $conj(cackle) with glee!",
        "target_self": "You cackle gleefully at {target}.",
        "target_room": "$You() $conj(cackle) gleefully at {target}.",
        "target_victim": "{actor} cackles gleefully at you.",
    },
    "cheer": {
        "no_target_self": "You cheer enthusiastically!",
        "no_target_room": "$You() $conj(cheer) enthusiastically!",
        "target_self": "You cheer for {target}!",
        "target_room": "$You() $conj(cheer) for {target}!",
        "target_victim": "{actor} cheers for you!",
        "self_self": "You cheer for yourself. Modest, aren't we?",
        "self_room": "$You() $conj(cheer) for $pron(yourself).",
    },
    "chuckle": {
        "no_target_self": "You chuckle softly.",
        "no_target_room": "$You() $conj(chuckle) softly.",
        "target_self": "You chuckle at {target}.",
        "target_room": "$You() $conj(chuckle) at {target}.",
        "target_victim": "{actor} chuckles at you.",
    },
    "clap": {
        "no_target_self": "You clap your hands together.",
        "no_target_room": "$You() $conj(clap) $pron(their) hands together.",
        "target_self": "You clap for {target}.",
        "target_room": "$You() $conj(clap) for {target}.",
        "target_victim": "{actor} claps for you.",
        "self_self": "You clap for yourself. Well done, you.",
        "self_room": "$You() $conj(clap) for $pron(yourself).",
    },
    "comfort": {
        "no_target_self": "You need to comfort someone specific.",
        "no_target_room": None,
        "target_self": "You comfort {target}.",
        "target_room": "$You() $conj(comfort) {target}.",
        "target_victim": "{actor} comforts you.",
        "self_self": "You comfort yourself. There, there.",
        "self_room": "$You() $conj(comfort) $pron(yourself).",
    },
    "cringe": {
        "no_target_self": "You cringe in embarrassment.",
        "no_target_room": "$You() $conj(cringe) in embarrassment.",
        "target_self": "You cringe away from {target}.",
        "target_room": "$You() $conj(cringe) away from {target}.",
        "target_victim": "{actor} cringes away from you.",
    },
    "cry": {
        "no_target_self": "You burst into tears.",
        "no_target_room": "$You() $conj(burst) into tears.",
        "target_self": "You cry on {target}'s shoulder.",
        "target_room": "$You() $conj(cry) on {target}'s shoulder.",
        "target_victim": "{actor} cries on your shoulder.",
        "self_self": "You cry to yourself.",
        "self_room": "$You() $conj(cry) to $pron(yourself).",
    },
    "curtsey": {
        "aliases": ["curtsy"],
        "no_target_self": "You curtsey gracefully.",
        "no_target_room": "$You() $conj(curtsey) gracefully.",
        "target_self": "You curtsey to {target}.",
        "target_room": "$You() $conj(curtsey) to {target}.",
        "target_victim": "{actor} curtseys to you.",
    },
    "dance": {
        "no_target_self": "You dance around the room!",
        "no_target_room": "$You() $conj(dance) around the room!",
        "target_self": "You grab {target} and dance!",
        "target_room": "$You() $conj(grab) {target} and $conj(dance)!",
        "target_victim": "{actor} grabs you and dances!",
        "self_self": "You dance with yourself. At least someone will.",
        "self_room": "$You() $conj(dance) alone.",
    },
    "drool": {
        "no_target_self": "You drool all over yourself.",
        "no_target_room": "$You() $conj(drool) all over $pron(yourself).",
        "target_self": "You drool all over {target}.",
        "target_room": "$You() $conj(drool) all over {target}.",
        "target_victim": "{actor} drools all over you.",
    },
    "facepalm": {
        "no_target_self": "You bury your face in your palm.",
        "no_target_room": "$You() $conj(bury) $pron(their) face in $pron(their) palm.",
        "target_self": "You facepalm at {target}.",
        "target_room": "$You() $conj(facepalm) at {target}.",
        "target_victim": "{actor} facepalms at you.",
    },
    "flex": {
        "no_target_self": "You flex your muscles impressively!",
        "no_target_room": "$You() $conj(flex) $pron(their) muscles impressively!",
        "target_self": "You flex your muscles at {target}.",
        "target_room": "$You() $conj(flex) $pron(their) muscles at {target}.",
        "target_victim": "{actor} flexes at you.",
    },
    "frown": {
        "no_target_self": "You frown.",
        "no_target_room": "$You() $conj(frown).",
        "target_self": "You frown at {target}.",
        "target_room": "$You() $conj(frown) at {target}.",
        "target_victim": "{actor} frowns at you.",
    },
    "gasp": {
        "no_target_self": "You gasp in astonishment!",
        "no_target_room": "$You() $conj(gasp) in astonishment!",
        "target_self": "You gasp at {target}.",
        "target_room": "$You() $conj(gasp) at {target}.",
        "target_victim": "{actor} gasps at you.",
    },
    "giggle": {
        "no_target_self": "You giggle.",
        "no_target_room": "$You() $conj(giggle).",
        "target_self": "You giggle at {target}.",
        "target_room": "$You() $conj(giggle) at {target}.",
        "target_victim": "{actor} giggles at you.",
    },
    "glare": {
        "no_target_self": "You glare at nothing in particular.",
        "no_target_room": "$You() $conj(glare) at nothing in particular.",
        "target_self": "You glare icily at {target}.",
        "target_room": "$You() $conj(glare) icily at {target}.",
        "target_victim": "{actor} glares icily at you.",
    },
    "grin": {
        "no_target_self": "You grin mischievously.",
        "no_target_room": "$You() $conj(grin) mischievously.",
        "target_self": "You grin mischievously at {target}.",
        "target_room": "$You() $conj(grin) mischievously at {target}.",
        "target_victim": "{actor} grins mischievously at you.",
    },
    "groan": {
        "no_target_self": "You groan loudly.",
        "no_target_room": "$You() $conj(groan) loudly.",
        "target_self": "You groan at {target}.",
        "target_room": "$You() $conj(groan) at {target}.",
        "target_victim": "{actor} groans at you.",
    },
    "grovel": {
        "no_target_self": "You grovel in the dirt.",
        "no_target_room": "$You() $conj(grovel) in the dirt.",
        "target_self": "You grovel before {target}.",
        "target_room": "$You() $conj(grovel) before {target}.",
        "target_victim": "{actor} grovels before you.",
    },
    "growl": {
        "no_target_self": "You growl menacingly.",
        "no_target_room": "$You() $conj(growl) menacingly.",
        "target_self": "You growl at {target}.",
        "target_room": "$You() $conj(growl) at {target}.",
        "target_victim": "{actor} growls at you.",
    },
    "high5": {
        "aliases": ["highfive"],
        "no_target_self": "You hold your hand up for a high five, but nobody's there.",
        "no_target_room": "$You() $conj(hold) $pron(their) hand up for a high five.",
        "target_self": "You high five {target}!",
        "target_room": "$You() $conj(high) $conj(five) {target}!",
        "target_victim": "{actor} high fives you!",
        "self_self": "You high five yourself. Slap!",
        "self_room": "$You() $conj(high) $conj(five) $pron(yourself).",
    },
    "hug": {
        "no_target_self": "You hug yourself.",
        "no_target_room": "$You() $conj(hug) $pron(yourself).",
        "target_self": "You hug {target} warmly.",
        "target_room": "$You() $conj(hug) {target} warmly.",
        "target_victim": "{actor} hugs you warmly.",
    },
    "kiss": {
        "no_target_self": "You pucker up, but there's no one to kiss.",
        "no_target_room": "$You() $conj(pucker) up, looking for someone to kiss.",
        "target_self": "You kiss {target}.",
        "target_room": "$You() $conj(kiss) {target}.",
        "target_victim": "{actor} kisses you.",
        "self_self": "You kiss the back of your hand.",
        "self_room": "$You() $conj(kiss) the back of $pron(their) hand.",
    },
    "laugh": {
        "aliases": ["lol"],
        "no_target_self": "You fall down laughing!",
        "no_target_room": "$You() $conj(fall) down laughing!",
        "target_self": "You laugh at {target}.",
        "target_room": "$You() $conj(laugh) at {target}.",
        "target_victim": "{actor} laughs at you.",
        "self_self": "You laugh at yourself.",
        "self_room": "$You() $conj(laugh) at $pron(yourself).",
    },
    "lick": {
        "no_target_self": "You lick your lips and smile.",
        "no_target_room": "$You() $conj(lick) $pron(their) lips and $conj(smile).",
        "target_self": "You lick {target}.",
        "target_room": "$You() $conj(lick) {target}.",
        "target_victim": "{actor} licks you.",
        "self_self": "You lick yourself. Yuck.",
        "self_room": "$You() $conj(lick) $pron(yourself). Yuck.",
    },
    "nod": {
        "no_target_self": "You nod solemnly.",
        "no_target_room": "$You() $conj(nod) solemnly.",
        "target_self": "You nod at {target}.",
        "target_room": "$You() $conj(nod) at {target}.",
        "target_victim": "{actor} nods at you.",
    },
    "nudge": {
        "no_target_self": "You need to nudge someone specific.",
        "no_target_room": None,
        "target_self": "You nudge {target}.",
        "target_room": "$You() $conj(nudge) {target}.",
        "target_victim": "{actor} nudges you.",
    },
    "pat": {
        "no_target_self": "You need to pat someone specific.",
        "no_target_room": None,
        "target_self": "You pat {target} on the head.",
        "target_room": "$You() $conj(pat) {target} on the head.",
        "target_victim": "{actor} pats you on the head.",
        "self_self": "You pat yourself on the back.",
        "self_room": "$You() $conj(pat) $pron(yourself) on the back.",
    },
    "peer": {
        "no_target_self": "You peer around the room suspiciously.",
        "no_target_room": "$You() $conj(peer) around the room suspiciously.",
        "target_self": "You peer at {target} suspiciously.",
        "target_room": "$You() $conj(peer) at {target} suspiciously.",
        "target_victim": "{actor} peers at you suspiciously.",
    },
    "point": {
        "no_target_self": "You point at nothing in particular.",
        "no_target_room": "$You() $conj(point) at nothing in particular.",
        "target_self": "You point at {target}.",
        "target_room": "$You() $conj(point) at {target}.",
        "target_victim": "{actor} points at you.",
        "self_self": "You point at yourself.",
        "self_room": "$You() $conj(point) at $pron(yourself).",
    },
    "poke": {
        "no_target_self": "You need to poke someone specific.",
        "no_target_room": None,
        "target_self": "You poke {target} in the ribs.",
        "target_room": "$You() $conj(poke) {target} in the ribs.",
        "target_victim": "{actor} pokes you in the ribs.",
        "self_self": "You poke yourself in the ribs. Ouch!",
        "self_room": "$You() $conj(poke) $pron(yourself) in the ribs.",
    },
    "ponder": {
        "no_target_self": "You ponder the situation.",
        "no_target_room": "$You() $conj(ponder) the situation.",
        "target_self": "You ponder what {target} said.",
        "target_room": "$You() $conj(ponder) what {target} said.",
        "target_victim": "{actor} ponders what you said.",
    },
    "pout": {
        "no_target_self": "You pout.",
        "no_target_room": "$You() $conj(pout).",
        "target_self": "You pout at {target}.",
        "target_room": "$You() $conj(pout) at {target}.",
        "target_victim": "{actor} pouts at you.",
    },
    "salute": {
        "no_target_self": "You salute smartly.",
        "no_target_room": "$You() $conj(salute) smartly.",
        "target_self": "You salute {target}.",
        "target_room": "$You() $conj(salute) {target}.",
        "target_victim": "{actor} salutes you.",
    },
    "shake": {
        "no_target_self": "You shake your head.",
        "no_target_room": "$You() $conj(shake) $pron(their) head.",
        "target_self": "You shake hands with {target}.",
        "target_room": "$You() $conj(shake) hands with {target}.",
        "target_victim": "{actor} shakes hands with you.",
    },
    "shrug": {
        "no_target_self": "You shrug helplessly.",
        "no_target_room": "$You() $conj(shrug) helplessly.",
        "target_self": "You shrug at {target}.",
        "target_room": "$You() $conj(shrug) at {target}.",
        "target_victim": "{actor} shrugs at you.",
    },
    "sigh": {
        "no_target_self": "You sigh deeply.",
        "no_target_room": "$You() $conj(sigh) deeply.",
        "target_self": "You sigh at {target}.",
        "target_room": "$You() $conj(sigh) at {target}.",
        "target_victim": "{actor} sighs at you.",
    },
    "slap": {
        "no_target_self": "You need to slap someone specific.",
        "no_target_room": None,
        "target_self": "You slap {target}!",
        "target_room": "$You() $conj(slap) {target}!",
        "target_victim": "{actor} slaps you!",
        "self_self": "You slap yourself. Snap out of it!",
        "self_room": "$You() $conj(slap) $pron(yourself).",
    },
    "smile": {
        "no_target_self": "You smile happily.",
        "no_target_room": "$You() $conj(smile) happily.",
        "target_self": "You smile at {target}.",
        "target_room": "$You() $conj(smile) at {target}.",
        "target_victim": "{actor} smiles at you.",
    },
    "smirk": {
        "no_target_self": "You smirk.",
        "no_target_room": "$You() $conj(smirk).",
        "target_self": "You smirk at {target}.",
        "target_room": "$You() $conj(smirk) at {target}.",
        "target_victim": "{actor} smirks at you.",
    },
    "snicker": {
        "no_target_self": "You snicker softly.",
        "no_target_room": "$You() $conj(snicker) softly.",
        "target_self": "You snicker at {target}.",
        "target_room": "$You() $conj(snicker) at {target}.",
        "target_victim": "{actor} snickers at you.",
    },
    "thank": {
        "aliases": ["thanks"],
        "no_target_self": "You thank everyone.",
        "no_target_room": "$You() $conj(thank) everyone.",
        "target_self": "You thank {target}.",
        "target_room": "$You() $conj(thank) {target}.",
        "target_victim": "{actor} thanks you.",
    },
    "wave": {
        "no_target_self": "You wave.",
        "no_target_room": "$You() $conj(wave).",
        "target_self": "You wave at {target}.",
        "target_room": "$You() $conj(wave) at {target}.",
        "target_victim": "{actor} waves at you.",
    },
    "wink": {
        "no_target_self": "You wink suggestively.",
        "no_target_room": "$You() $conj(wink) suggestively.",
        "target_self": "You wink at {target}.",
        "target_room": "$You() $conj(wink) at {target}.",
        "target_victim": "{actor} winks at you.",
    },
    "yawn": {
        "no_target_self": "You yawn widely.",
        "no_target_room": "$You() $conj(yawn) widely.",
        "target_self": "You yawn at {target}. How rude.",
        "target_room": "$You() $conj(yawn) at {target}.",
        "target_victim": "{actor} yawns at you. How rude.",
    },
}
