from world.prototypes.weapons.training_dagger import *     # noqa: F401,F403
from world.prototypes.weapons.training_shortsword import * # noqa: F401,F403
from world.prototypes.weapons.training_longsword import *  # noqa: F401,F403
from world.prototypes.weapons.training_bow import *        # noqa: F401,F403
from world.prototypes.weapons.club import *                # noqa: F401,F403
from world.prototypes.weapons.iron_dagger import *         # noqa: F401,F403
from world.prototypes.weapons.iron_shortsword import *     # noqa: F401,F403
from world.prototypes.weapons.iron_longsword import *      # noqa: F401,F403
from world.prototypes.weapons.iron_hand_axe import *       # noqa: F401,F403
from world.prototypes.weapons.iron_spear import *      # noqa: F401,F403
from world.prototypes.weapons.iron_mace import *           # noqa: F401,F403
from world.prototypes.weapons.iron_hammer import *         # noqa: F401,F403
from world.prototypes.weapons.training_greatsword import * # noqa: F401,F403
from world.prototypes.weapons.bronze_dagger import *      # noqa: F401,F403
from world.prototypes.weapons.bronze_shortsword import *  # noqa: F401,F403
from world.prototypes.weapons.bronze_longsword import *   # noqa: F401,F403
from world.prototypes.weapons.bronze_hand_axe import *    # noqa: F401,F403
from world.prototypes.weapons.bronze_spear import *       # noqa: F401,F403
from world.prototypes.weapons.bronze_mace import *        # noqa: F401,F403
from world.prototypes.weapons.bronze_hammer import *      # noqa: F401,F403
from world.prototypes.weapons.sling import *              # noqa: F401,F403
from world.prototypes.weapons.shortbow import *          # noqa: F401,F403
from world.prototypes.weapons.quarterstaff import *      # noqa: F401,F403
from world.prototypes.weapons.training_lance import *    # noqa: F401,F403
from world.prototypes.weapons.crossbow import *          # noqa: F401,F403
from world.prototypes.weapons.iron_spiked_club import *  # noqa: F401,F403
from world.prototypes.weapons.bronze_greatsword import * # noqa: F401,F403
from world.prototypes.weapons.bronze_battleaxe import *  # noqa: F401,F403
from world.prototypes.weapons.bronze_rapier import *     # noqa: F401,F403
from world.prototypes.weapons.shepherds_sling import *   # noqa: F401,F403
