# Generated by Django 6.0.7 on 2026-08-26 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EconomySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour", models.DateTimeField(unique=True)),
                (
                    "players_online",
                    models.IntegerField(
                        default=0, help_text="Players online at snapshot time"
                    ),
                ),
                (
                    "unique_players_1h",
                    models.IntegerField(
                        default=0, help_text="Distinct accounts active in past hour"
                    ),
                ),
                (
                    "unique_players_24h",
                    models.IntegerField(
                        default=0, help_text="Distinct accounts active in past 24 hours"
                    ),
                ),
                (
                    "unique_players_7d",
                    models.IntegerField(
                        default=0, help_text="Distinct accounts active in past 7 days"
                    ),
                ),
                (
                    "gold_circulation",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Total gold in CHARACTER + ACCOUNT locations",
                        max_digits=36,
                    ),
                ),
                (
                    "gold_reserve",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Total gold in RESERVE location",
                        max_digits=36,
                    ),
                ),
                (
                    "gold_sinks_1h",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Gold in SINK location (consumed, awaiting reallocation)",
                        max_digits=36,
                    ),
                ),
                (
                    "gold_spawned_1h",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Gold spawned (pickup from SPAWNED) in the past hour",
                        max_digits=36,
                    ),
                ),
                (
                    "amm_trades_1h",
                    models.IntegerField(
                        default=0, help_text="Number of AMM trades in the past hour"
                    ),
                ),
                (
                    "amm_volume_gold_1h",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Total gold volume through AMM in the past hour",
                        max_digits=36,
                    ),
                ),
                (
                    "imports_1h",
                    models.IntegerField(
                        default=0,
                        help_text="Fungible imports from chain in the past hour",
                    ),
                ),
                (
                    "exports_1h",
                    models.IntegerField(
                        default=0,
                        help_text="Fungible exports to chain in the past hour",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-hour"],
            },
        ),
        migrations.CreateModel(
            name="PlayerSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_id",
                    models.IntegerField(help_text="Evennia account ID (AccountDB.id)"),
                ),
                (
                    "character_key",
                    models.CharField(
                        help_text="Character db_key at session start", max_length=80
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["started_at"], name="tele_session_started_idx"
                    ),
                    models.Index(
                        fields=["account_id", "started_at"],
                        name="tele_session_acct_start_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ResourceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour", models.DateTimeField()),
                ("currency_code", models.CharField(max_length=40)),
                (
                    "in_character",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Total in player inventories",
                        max_digits=36,
                    ),
                ),
                (
                    "in_account",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Total in player banks",
                        max_digits=36,
                    ),
                ),
                (
                    "in_spawned",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Total spawned in world (ground, mob loot, chests)",
                        max_digits=36,
                    ),
                ),
                (
                    "in_reserve",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Total in game vault reserve",
                        max_digits=36,
                    ),
                ),
                (
                    "in_sink",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="Total consumed (fees, crafting, dust) awaiting reallocation",
                        max_digits=36,
                    ),
                ),
                (
                    "produced_1h",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="craft_output + pickup (from SPAWNED) in past hour",
                        max_digits=36,
                    ),
                ),
                (
                    "consumed_1h",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="craft_input in past hour",
                        max_digits=36,
                    ),
                ),
                (
                    "traded_1h",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="amm_buy + amm_sell volume (resource side) in past hour",
                        max_digits=36,
                    ),
                ),
                (
                    "exported_1h",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="withdraw_to_chain in past hour",
                        max_digits=36,
                    ),
                ),
                (
                    "imported_1h",
                    models.DecimalField(
                        decimal_places=6,
                        default=0,
                        help_text="deposit_from_chain in past hour",
                        max_digits=36,
                    ),
                ),
                (
                    "amm_buy_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Gold cost to buy 1 unit from AMM",
                        max_digits=36,
                        null=True,
                    ),
                ),
                (
                    "amm_sell_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Gold received from selling 1 unit to AMM",
                        max_digits=36,
                        null=True,
                    ),
                ),
                (
                    "spawn_budget",
                    models.IntegerField(
                        default=0, help_text="Calculator budget for this hour"
                    ),
                ),
                (
                    "spawn_quest_debt",
                    models.IntegerField(
                        default=0, help_text="Budget redirected to quest rewards"
                    ),
                ),
                (
                    "spawn_placed",
                    models.IntegerField(
                        default=0, help_text="Units actually placed on targets"
                    ),
                ),
                (
                    "spawn_dropped",
                    models.IntegerField(
                        default=0,
                        help_text="Surplus dropped (no targets with headroom)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-hour"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hour", "currency_code"),
                        name="telemetry_unique_resource_hour",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SaturationSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hour", models.DateTimeField()),
                ("item_key", models.CharField(max_length=80)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("spell", "Spell"),
                            ("recipe", "Recipe"),
                            ("item", "Item"),
                        ],
                        max_length=10,
                    ),
                ),
                ("active_players_7d", models.IntegerField()),
                ("eligible_players", models.IntegerField(default=0)),
                ("known_by", models.IntegerField(default=0)),
                ("unlearned_copies", models.IntegerField(default=0)),
                ("in_circulation", models.IntegerField(default=0)),
                ("saturation", models.FloatField(default=0.0)),
                (
                    "spawn_budget",
                    models.IntegerField(
                        default=0, help_text="Calculator budget for this cycle"
                    ),
                ),
                (
                    "spawn_quest_debt",
                    models.IntegerField(
                        default=0, help_text="Budget redirected to quest rewards"
                    ),
                ),
                (
                    "spawn_placed",
                    models.IntegerField(
                        default=0, help_text="Units actually placed on targets"
                    ),
                ),
                (
                    "spawn_dropped",
                    models.IntegerField(
                        default=0,
                        help_text="Surplus dropped (no targets with headroom)",
                    ),
                ),
            ],
            options={
                "ordering": ["-hour"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("hour", "item_key", "category"),
                        name="telemetry_unique_saturation_hour_item",
                    )
                ],
            },
        ),
    ]
