from world.prototypes.consumables.recipes.training_longsword_recipe import *        # noqa: F401,F403
from world.prototypes.consumables.recipes.training_dagger_recipe import *          # noqa: F401,F403
from world.prototypes.consumables.recipes.training_shortsword_recipe import *      # noqa: F401,F403
from world.prototypes.consumables.recipes.training_bow_recipe import *             # noqa: F401,F403
from world.prototypes.consumables.recipes.club_recipe import *                     # noqa: F401,F403
from world.prototypes.consumables.recipes.bronze_spiked_club_recipe import *      # noqa: F401,F403
from world.prototypes.consumables.recipes.shaft_recipe import *                    # noqa: F401,F403
from world.prototypes.consumables.recipes.haft_recipe import *                    # noqa: F401,F403
from world.prototypes.consumables.recipes.training_greatsword_recipe import *    # noqa: F401,F403
from world.prototypes.consumables.recipes.wooden_shield_recipe import *            # noqa: F401,F403
from world.prototypes.consumables.recipes.iron_dagger_recipe import *              # noqa: F401,F403
from world.prototypes.consumables.recipes.iron_shortsword_recipe import *          # noqa: F401,F403
from world.prototypes.consumables.recipes.iron_longsword_recipe import *           # noqa: F401,F403
from world.prototypes.consumables.recipes.iron_hand_axe_recipe import *            # noqa: F401,F403
from world.prototypes.consumables.recipes.spear_recipe import *                    # noqa: F401,F403
from world.prototypes.consumables.recipes.ironbound_shield_recipe import *       # noqa: F401,F403
from world.prototypes.consumables.recipes.crossbow_recipe import *              # noqa: F401,F403
from world.prototypes.consumables.recipes.iron_spiked_club_recipe import *     # noqa: F401,F403
from world.prototypes.consumables.recipes.studded_leather_armor_recipe import * # noqa: F401,F403
from world.prototypes.consumables.recipes.bronze_dagger_recipe import *          # noqa: F401,F403
from world.prototypes.consumables.recipes.bronze_shortsword_recipe import *      # noqa: F401,F403
from world.prototypes.consumables.recipes.bronze_longsword_recipe import *       # noqa: F401,F403
from world.prototypes.consumables.recipes.bronze_hand_axe_recipe import *        # noqa: F401,F403
from world.prototypes.consumables.recipes.bronze_spear_recipe import *           # noqa: F401,F403
from world.prototypes.consumables.recipes.bronze_mace_recipe import *            # noqa: F401,F403
from world.prototypes.consumables.recipes.bronze_hammer_recipe import *          # noqa: F401,F403
from world.prototypes.consumables.recipes.bronze_greatsword_recipe import *     # noqa: F401,F403
from world.prototypes.consumables.recipes.bronze_battleaxe_recipe import *      # noqa: F401,F403
from world.prototypes.consumables.recipes.bronze_rapier_recipe import *         # noqa: F401,F403
from world.prototypes.consumables.recipes.bronze_greaves_recipe import *      # noqa: F401,F403
from world.prototypes.consumables.recipes.bronze_bracers_recipe import *      # noqa: F401,F403
from world.prototypes.consumables.recipes.bronze_helm_recipe import *         # noqa: F401,F403
from world.prototypes.consumables.recipes.leather_boots_recipe import *            # noqa: F401,F403
from world.prototypes.consumables.recipes.leather_gloves_recipe import *           # noqa: F401,F403
from world.prototypes.consumables.recipes.leather_belt_recipe import *             # noqa: F401,F403
from world.prototypes.consumables.recipes.leather_cap_recipe import *             # noqa: F401,F403
from world.prototypes.consumables.recipes.leather_pants_recipe import *            # noqa: F401,F403
from world.prototypes.consumables.recipes.bridle_recipe import *                   # noqa: F401,F403
from world.prototypes.consumables.recipes.gambeson_recipe import *                 # noqa: F401,F403
from world.prototypes.consumables.recipes.coarse_robe_recipe import *              # noqa: F401,F403
from world.prototypes.consumables.recipes.kippah_recipe import *                   # noqa: F401,F403
from world.prototypes.consumables.recipes.brown_corduroy_pants_recipe import *     # noqa: F401,F403
from world.prototypes.consumables.recipes.bandana_recipe import *                 # noqa: F401,F403
from world.prototypes.consumables.recipes.cloak_recipe import *                   # noqa: F401,F403
from world.prototypes.consumables.recipes.veil_recipe import *                    # noqa: F401,F403
from world.prototypes.consumables.recipes.scarf_recipe import *                   # noqa: F401,F403
from world.prototypes.consumables.recipes.sash_recipe import *                    # noqa: F401,F403
from world.prototypes.consumables.recipes.warriors_wraps_recipe import *          # noqa: F401,F403
from world.prototypes.consumables.recipes.backpack_recipe import *                # noqa: F401,F403
from world.prototypes.consumables.recipes.panniers_recipe import *                 # noqa: F401,F403
from world.prototypes.consumables.recipes.sling_recipe import *                   # noqa: F401,F403
from world.prototypes.consumables.recipes.leather_straps_recipe import *          # noqa: F401,F403
from world.prototypes.consumables.recipes.leather_armor_recipe import *           # noqa: F401,F403
from world.prototypes.consumables.recipes.copper_ring_recipe import *              # noqa: F401,F403
from world.prototypes.consumables.recipes.copper_chain_recipe import *             # noqa: F401,F403
from world.prototypes.consumables.recipes.copper_bangle_recipe import *            # noqa: F401,F403
from world.prototypes.consumables.recipes.copper_studs_recipe import *             # noqa: F401,F403
from world.prototypes.consumables.recipes.pewter_ring_recipe import *              # noqa: F401,F403
from world.prototypes.consumables.recipes.pewter_chain_recipe import *             # noqa: F401,F403
from world.prototypes.consumables.recipes.pewter_bracelet_recipe import *          # noqa: F401,F403
from world.prototypes.consumables.recipes.pewter_hoops_recipe import *             # noqa: F401,F403
from world.prototypes.consumables.recipes.lifes_essence_recipe import *            # noqa: F401,F403
from world.prototypes.consumables.recipes.the_zephyr_recipe import *               # noqa: F401,F403
from world.prototypes.consumables.recipes.the_wellspring_recipe import *           # noqa: F401,F403
from world.prototypes.consumables.recipes.the_bull_recipe import *                 # noqa: F401,F403
from world.prototypes.consumables.recipes.cats_grace_recipe import *               # noqa: F401,F403
from world.prototypes.consumables.recipes.the_bear_recipe import *                 # noqa: F401,F403
from world.prototypes.consumables.recipes.foxs_cunning_recipe import *             # noqa: F401,F403
from world.prototypes.consumables.recipes.owls_insight_recipe import *             # noqa: F401,F403
from world.prototypes.consumables.recipes.silver_tongue_recipe import *            # noqa: F401,F403
from world.prototypes.consumables.recipes.wooden_torch_recipe import *            # noqa: F401,F403
from world.prototypes.consumables.recipes.bronze_lantern_recipe import *          # noqa: F401,F403
