"""
LLMRoleplayNPC — pre-built LLM-powered roleplay NPC.

For shopkeepers, innkeepers, guards, townsfolk, etc. who respond to
directed speech with in-character dialogue generated by an LLM.

Usage (in a spawn script)::

    from evennia.utils.create import create_object
    from typeclasses.actors.npcs.llm_roleplay_npc import LLMRoleplayNPC

    npc = create_object(
        LLMRoleplayNPC,
        key="Greta the Innkeeper",
        location=inn_room,
    )
    npc.llm_personality = (
        "A warm, matronly innkeeper who gossips about local events "
        "and always tries to get people to try the stew."
    )
    npc.llm_knowledge = (
        "The inn serves ale for 2 gold and stew for 3 gold. "
        "Rooms cost 10 gold per night. The cellar is off-limits."
    )
"""

from evennia.typeclasses.attributes import AttributeProperty

from typeclasses.actors.npc import BaseNPC
from typeclasses.mixins.llm_mixin import LLMMixin


class LLMRoleplayNPC(LLMMixin, BaseNPC):
    """
    Roleplay NPC with LLM-powered dialogue.

    Responds to ``sayto`` commands with in-character speech generated
    by an LLM via OpenRouter. Falls back to a generic emote if the
    LLM is unavailable or rate-limited.

    Set ``llm_listens_ambient = True`` for NPCs that overhear and
    interject in room conversations (e.g. the annoying bar patron).
    """

    llm_prompt_file = AttributeProperty("roleplay_npc.md")

    def at_object_creation(self):
        super().at_object_creation()
        self.at_llm_init()

    def llm_fallback_response(self, speaker, interaction_type):
        """Fallback when LLM is unavailable."""
        if interaction_type == "sayto":
            return f"*nods at {speaker.key} thoughtfully*"
        return None
