# Generated by Django 6.0.3 on 2026-03-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xrpl", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="bulletinlisting",
            new_name="xrpl_bullet_expires_71139f_idx",
            old_name="xrpl_bulletinli_expires_idx",
        ),
        migrations.AlterField(
            model_name="fungiblegamestate",
            name="location",
            field=models.CharField(
                choices=[
                    ("RESERVE", "Reserve"),
                    ("SPAWNED", "Spawned"),
                    ("ACCOUNT", "Account"),
                    ("CHARACTER", "Character"),
                    ("SINK", "Sink"),
                ],
                default="RESERVE",
                max_length=10,
            ),
        ),
    ]
