# Generated by Django 6.0.7 on 2026-08-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("xrpl", "0004_enchantmentslot"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReconciliationFailure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        help_text="Method that failed, e.g. deposit_gold_from_chain",
                        max_length=40,
                    ),
                ),
                ("wallet_address", models.CharField(db_index=True, max_length=50)),
                (
                    "character_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "currency_code",
                    models.CharField(blank=True, max_length=40, null=True),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=36, null=True
                    ),
                ),
                ("tx_hash", models.CharField(blank=True, max_length=64, null=True)),
                (
                    "error",
                    models.TextField(
                        help_text="Exception text, for whoever picks this up"
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(
                        default=False, help_text="Set once someone has put it right"
                    ),
                ),
                ("resolved_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reconciliation Failure",
                "verbose_name_plural": "Reconciliation Failures",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["resolved"], name="xrpl_reconfail_resolved_idx"
                    )
                ],
            },
        ),
    ]
