# Generated by Django 6.0.7 on 2026-08-26 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("xrpl", "0005_reconciliationfailure"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EconomySnapshot",
        ),
        migrations.RemoveIndex(
            model_name="playersession",
            name="xrpl_session_started_idx",
        ),
        migrations.RemoveIndex(
            model_name="playersession",
            name="xrpl_session_acct_started_idx",
        ),
        migrations.DeleteModel(
            name="PlayerSession",
        ),
        migrations.RemoveConstraint(
            model_name="resourcesnapshot",
            name="xrpl_unique_resource_snapshot_hour",
        ),
        migrations.DeleteModel(
            name="ResourceSnapshot",
        ),
        migrations.RemoveConstraint(
            model_name="saturationsnapshot",
            name="xrpl_unique_saturation_hour_item",
        ),
        migrations.DeleteModel(
            name="SaturationSnapshot",
        ),
    ]
